services:
  database:
    build: ./postgresql
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "$POSTGRES_DB", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data-migrate

  migrate:
    build: ./app
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
        restart: false
    networks:
      - data-migrate

volumes:
  database_data:

networks:
  data-migrate: 
    driver: bridge